# SRC_DIR may be overridden with environment variable
SRC_DIR ?= ../../mulib

MODULE_NAME := test_mu_sched
SRC_FILES := \
    $(SRC_DIR)/mu_queue.c \
    $(SRC_DIR)/mu_sched.c \
    $(SRC_DIR)/mu_spsc.c \
    $(SRC_DIR)/mu_task.c

include ../make_common.mk
